/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./docs/**/*.md",
    "./docs/.vitepress/**/*.vue",
    "./docs/.vitepress/**/*.ts",
    "./docs/.vitepress/**/*.mts",
    "./docs/.vitepress/**/*.js",
  ],
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#bfcaff",
        "surface-container-high": "#272a31",
        "tertiary-fixed": "#56ffa8",
        "on-secondary-fixed": "#001f24",
        "surface-variant": "#32353c",
        "status-warn": "#FFB800",
        "surface-tint": "#b7c4ff",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-low": "#191c22",
        "on-tertiary": "#00391f",
        "on-surface-variant": "#c5c5d3",
        "surface-charcoal": "#161B22",
        "secondary-fixed": "#9cf0ff",
        "border-muted": "#30363D",
        "secondary": "#bdf4ff",
        "outline-variant": "#444651",
        "text-dim": "#8B949E",
        "primary": "#b7c4ff",
        "surface-dim": "#10131a",
        "terminal-black": "#0B0E14",
        "inverse-primary": "#4459a9",
        "background": "#10131a",
        "surface-container-highest": "#32353c",
        "surface-bright": "#363940",
        "on-tertiary-fixed": "#002110",
        "surface-container-lowest": "#0b0e14",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004f58",
        "outline": "#8f909c",
        "secondary-container": "#00e3fd",
        "status-fail": "#FF4B4B",
        "tertiary-fixed-dim": "#00e38b",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#00daf3",
        "primary-fixed": "#dde1ff",
        "surface-container": "#1d2026",
        "primary-container": "#3c51a1",
        "on-surface": "#e1e2eb",
        "surface": "#10131a",
        "inverse-on-surface": "#2e3037",
        "on-secondary": "#00363d",
        "tertiary-container": "#00643a",
        "error": "#ffb4ab",
        "on-secondary-container": "#00616d",
        "on-primary": "#0e2879",
        "on-tertiary-container": "#00ea8f",
        "on-background": "#e1e2eb",
        "inverse-surface": "#e1e2eb",
        "on-primary-fixed": "#001452",
        "on-error": "#690005",
        "status-pass": "#00FF9D",
        "on-primary-fixed-variant": "#2b4090",
        "tertiary": "#00e38b",
        "on-tertiary-fixed-variant": "#00522f",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "container-max": "1200px",
        "gutter": "24px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "code-md": ["JetBrains Mono"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "450" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
