export const AGENTDOCS_PACKAGE_NAME = "AgentDocs";

export {
  AgentDocsConfigSchema,
  ConfigValidationError,
  parseConfig,
} from "./config.js";
export type { AgentDocsConfig } from "./config.js";
export {
  AgentMapSchema,
  AgentSetupSnippetSchema,
  BuildStateSchema,
  CodeBlockSchema,
  ContextFacetSchema,
  ChunkSchema,
  ContextBundleSchema,
  ContextVerificationSchema,
  GoalBundleSchema,
  HandoffBundleSchema,
  CrawlManifestSchema,
  DocPageSchema,
  EdgeSchema,
  EdgeTypeSchema,
  EntitySchema,
  EntityTypeSchema,
  EvidenceSchema,
  GotchaSchema,
  HeadingSchema,
  IngestManifestSchema,
  LinkSchema,
  ManifestSchema,
  MissingMetricReasonSchema,
  SkipReasonSchema,
  ReadinessCategorySchema,
  ReadinessCheckResultSchema,
  ReadinessReportSchema,
  SearchDocumentSchema,
  SearchIndexFallbackSchema,
  SearchResponseSchema,
  SearchResultSchema,
  SourceCoverageSchema,
  SourceLimitDiagnosticsSchema,
  StatusReportSchema,
  TaskPackSchema,
  TaskStepSchema,
  TryResultSchema,
} from "./models.js";
export type {
  AgentMap,
  AgentSetupSnippet,
  BuildState,
  CodeBlock,
  ContextFacet,
  Chunk,
  ContextBundle,
  ContextVerification,
  GoalBundle,
  HandoffBundle,
  CrawlManifest,
  DocPage,
  Edge,
  EdgeType,
  Entity,
  EntityType,
  Evidence,
  Gotcha,
  Heading,
  IngestManifest,
  Link,
  Manifest,
  MissingMetricReason,
  SkipReason,
  ReadinessCategory,
  ReadinessCheckResult,
  ReadinessReport,
  SearchDocument,
  SearchIndexFallback,
  SearchResponse,
  SearchResult,
  SourceCoverage,
  SourceLimitConfig,
  SourceLimitDiagnostics,
  StatusReport,
  TaskPack,
  TaskStep,
  TryResult,
} from "./models.js";
