export const AGENTDOCS_PACKAGE_NAME = "AgentDocs";

export {
  AgentDocsConfigSchema,
  ConfigValidationError,
  parseConfig,
} from "./config.js";
export type { AgentDocsConfig } from "./config.js";
export {
  AgentMapSchema,
  CodeBlockSchema,
  ChunkSchema,
  CrawlManifestSchema,
  DocPageSchema,
  EdgeSchema,
  EdgeTypeSchema,
  EntitySchema,
  EntityTypeSchema,
  EvidenceSchema,
  GotchaSchema,
  HeadingSchema,
  IngestManifestSchema,
  LinkSchema,
  ManifestSchema,
  ReadinessCategorySchema,
  ReadinessCheckResultSchema,
  ReadinessReportSchema,
  SearchDocumentSchema,
  SearchIndexFallbackSchema,
  SearchResponseSchema,
  SearchResultSchema,
  TaskPackSchema,
  TaskStepSchema,
} from "./models.js";
export type {
  AgentMap,
  CodeBlock,
  Chunk,
  CrawlManifest,
  DocPage,
  Edge,
  EdgeType,
  Entity,
  EntityType,
  Evidence,
  Gotcha,
  Heading,
  IngestManifest,
  Link,
  Manifest,
  ReadinessCategory,
  ReadinessCheckResult,
  ReadinessReport,
  SearchDocument,
  SearchIndexFallback,
  SearchResponse,
  SearchResult,
  TaskPack,
  TaskStep,
} from "./models.js";
